1. Use * to repeat the list [10, 1, 3.3] FIVE times 


In [2]:
list=[10,1,3.3]
five_times=list*5
five_times

[10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3, 10, 1, 3.3]

In [10]:
my_list = [1, 2, 3, 4, 5]
is_three_in_list = 3 in my_list
is_three_in_list



True

3. Now look at strings x = 'This is a string'
   
	(a) print first character
	(b) print first two characters
	(c) Print the last element of the string.
	(d) Print 4th element from the end and stop before the 2nd element from the end.
	(e) Slice starting from the 4th element from the end and stopping before the 4nd element from the end.
	(f) Slice from the beginning of the string and stopping before the 3rd element.
	(g) Slice starting from the 4th element of the string and going all the way to the end.

In [26]:
x = 'This is a string'
print("(a) first character=", x[0])
print("(b) first two characters = ", x[:2])
print("(c) the last element of the string =", x[-1])
print("(d) Print 4th element from the end and stop before the 2nd element from the end = ", x[-4:-1])
print("(e) Slice starting from the 4th element from the end and stopping before the 4nd element from the end = " , x[-4:-3])
print("(f) Slice from the beginning of the string and stopping before the 3rd element= ", x[:2])
print("(g) Slice starting from the 4th element of the string and going all the way to the end. = " , x[3:])

(a) first character= T
(b) first two characters =  Th
(c) the last element of the string = g
(d) Print 4th element from the end and stop before the 2nd element from the end =  rin
(e) Slice starting from the 4th element from the end and stopping before the 4nd element from the end =  r
(f) Slice from the beginning of the string and stopping before the 3rd element=  Th
(g) Slice starting from the 4th element of the string and going all the way to the end. =  s is a string


4. firstname = 'Arockiaraj'
   lastname = 'S'

	print concatenate firstname and lastname 
	
	print whether 'rock' is present in firstname.

In [31]:
firstname = 'Arockiaraj'
lastname = 'S'
print(firstname + " " + lastname)
check = 'rock' in firstname
check

Arockiaraj S


True

5. Split returns a list of all the words in a string, or a list split on a specific character.

	name = 'Tom Mitchell Machine Learning Scientist'.split(' ')
	

	(a) selects the first element of the list
	(b) selects the last element of the list
	(c) print the firstname
	(d) print middlename
	(e) print lastname
	(f) print firstname + ' ' + middlename+ ' ' + lastname

In [40]:
name = 'Tom Mitchell Machine Learning Scientist'.split(' ')
name = 'Tom Mitchell Machine Learning Scientist'.split(' ')
first_ele = name[0]
print(first_ele)

last_ele = name[-1]
print(last_ele)

firstname = name[0]
print(firstname)

middlename = name[1:-1]
print(' '.join(middlename))

lastname = name[-1]
print(lastname)

full_name = firstname + ' ' + ' '.join(middlename) + ' ' + lastname
print(full_name)

Tom
Scientist
Tom
Mitchell Machine Learning
Scientist
Tom Mitchell Machine Learning Scientist


6. Concatenate the following.
	Chris & 2 

In [45]:
x = 'chris'
y = 2
x + str(y)


'chris2'

7. Consider the dictionaries associate keys with values.
	x = {'Arockiaraj': 'araj.s@manipal.edu', 'Bill Gates': 'billg@microsoft.com'}
   
	(a) Retrieve a value by using the indexing operator
	(b) Iterate over all of the keys
	(c) Iterate over all of the values
	(d) Iterate over all of the items in the list

In [56]:
x = {'Arockiaraj': 'araj.s@manipal.edu', 'Bill Gates': 'billg@microsoft.com'}#arock-keys and email is value
print("(a)=" , x['Arockiaraj'])

for key in x.keys():
    print("(b=)",key)

for value in x.values():
    print("(c=)",value)
    
for item in x.items():
    print("(d=)", item)


(a)= araj.s@manipal.edu
(b=) Arockiaraj
(b=) Bill Gates
(c=) araj.s@manipal.edu
(c=) billg@microsoft.com
(d=) ('Arockiaraj', 'araj.s@manipal.edu')
(d=) ('Bill Gates', 'billg@microsoft.com')


8. Unpack a sequence into different variables: fname, lname, email
	x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu')

In [61]:
x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu')

fname, lname, email = x

print(f"First Name: {fname}")
print(f"Last Name: {lname}")
print(f"Email: {email}")


First Name: Arockiaraj
Last Name: Simiyon
Email: araj.s@manipal.edu


9. Make sure the number of values you are unpacking matches the number of variables being assigned.
	x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu', 'Manipal')
	fname, lname, email, mname = x


In [63]:
x = ('Arockiaraj', 'Simiyon', 'araj.s@manipal.edu', 'Manipal')
fname, lname, email, mname = x

print(f"First Name: {fname}")
print(f"Last Name: {lname}")
print(f"Email: {email}")
print(f"Middle Name: {mname}")



First Name: Arockiaraj
Last Name: Simiyon
Email: araj.s@manipal.edu
Middle Name: Manipal
f: Arockiaraj


10. Python has a built in method for convenient string formatting. 
	Explain the output of the following code.  

	sales_record = {'price': 3.24, 'num_items': 4, 'person': 'Arockiaraj', 'email':'araj.s@manipal.edu'}

	sales_statement = '{} bought {} item(s) at a price of INR {} each for a total of INR {}'

	print(sales_statement.format(sales_record['person'],
                             sales_record['num_items'],
                             sales_record['price'],
                             sales_record['num_items']*sales_record['price']))

In [69]:
sales_record = {'price': 3.24, 'num_items': 4, 'person': 'Arockiaraj', 'email':'araj.s@manipal.edu'}

sales_statement = '{} bought {} item(s) at a price of INR {} each for a total of INR {}'

print(sales_statement.format(person=sales_record['person'],
                             num_items=sales_record['num_items'],
                             price=sales_record['price'],
                             total=sales_record['num_items']*sales_record['price']))


Arockiaraj bought 4 item(s) at a price of INR 3.24 each for a total of INR 12.96


In [73]:
#11. Date and time use

import datetime as dt
import time as tm

# time returns the current time in seconds since the Epoch. (January 1st, 1970)
tm.time()

from datetime import date
today = date.today()
print('today date is', today)

# Convert the timestamp to datetime.
dtnow = dt.datetime.fromtimestamp(tm.time())
dtnow

# Handy datetime attributes:
dtnow.year, dtnow.month, dtnow.day, dtnow.hour, dtnow.minute, dtnow.second # get year, month, day, etc. from a datetime

# timedelta is a duration expressing the difference between two dates.
delta = dt.timedelta(days = 100) # create a timedelta of 100 days

# date.today returns the current local date.
today = dt.date.today()
today - delta # the date 100 days ago
today > today-delta # compare dates

today date is 2024-10-07


True

12. Objects and map()

#An example of a class in python:

class Person:
    institute = 'Manipal School of Information Sciences' #a class variable

    #self keyword to access the attributes and methods of the class
    
    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):  
        self.location = new_location

person = Person()
person.set_name('Arockiaraj')
person.set_location('Manipal, Udupi, Karnataka')

#what will be the output of the following statement:
print('{} lives in {} and works in the institute {}'.format(person.name, person.location, person.institute))


In [78]:
#12. Objects and map()

#An example of a class in python:

class Person:
    institute = 'Manipal School of Information Sciences' #a class variable

    #self keyword to access the attributes and methods of the class
    
    def set_name(self, new_name): #a method
        self.name = new_name
    def set_location(self, new_location):  
        self.location = new_location

person = Person()
person.set_name('Arockiaraj')
person.set_location('Manipal, Udupi, Karnataka')

#what will be the output of the following statement:
print('{} lives in {} and works in the institute {}'.format(person.name, person.location, person.institute))


Arockiaraj lives in Manipal, Udupi, Karnataka and works in the institute Manipal School of Information Sciences


In [82]:
#13. Example set

x={1, 'x', 2, 'y', (1, 2, 3), 'hello'}
y = (1, 2, 3)

	#sets are unordered 
y={1, 'x', 2, 'y'}
z={1, 'x', 2, 'y'}
print(y, z)

	#Write the output of the after executing the following commands: 
y.add(4)
z.add('a')
print(y, z)

{'y', 'x', 2, 1} {'y', 'x', 2, 1}
{1, 'x', 2, 4, 'y'} {1, 'x', 2, 'a', 'y'}


In [85]:
#Here's an example of mapping the min function between three lists. 
#Milk, water, sugar, tea packet

store1 = [10.00, 11.00, 12.34, 5.34]
store2 = [19.00, 10.10, 12.34, 5.01]
store3 = [15.00, 12.00, 11.00, 6.00]

cheapest = map(min, store1, store2, store3)
costly = map(max, store1, store2, store3)

print(cheapest)

# (a) Iterate through the map object to see the values.
for price in cheapest:
    print(price)
# (b) Iterate through the map object to see the values.
for price in costly:
    print(price)

10.0
10.1
11.0
5.01
19.0
12.0
12.34
6.0


In [86]:
#15. Use the following map function to find the square of the numbers

def calculateSquare(n):
    return n*n

numbers = (1, 2, 3, 4)
result = map(calculateSquare, numbers)
print (result)

#(a) what will be the output of the following:

for item in result:
    print(item)

1
4
9
16


In [88]:
#16. Lambda function is used when you need a function for a short period of time.
	

numbers = (1, 2, 3, 4)
result = map(lambda x: x*x, numbers)

#(a) Iterate through the map object to see the values.
for i in result:
    print(i)

1
4
9
16


In [90]:
#17.

num1 = [4, 5, 6]
num2 = [5, 6, 7]

result = map(lambda n1, n2: n1+n2, num1, num2)


#(a) Iterate through }the map object to see the values.
for i in result:
    print(i)

9
11
13


In [97]:
people = ['Python Programming Language', 'Computer Lab Test', 'Vinod Scored A', 'Kumar Scored B']

def split_title_and_name(person):
    title = person.split()[0]
    lastname = person.split()[-1]
    return '{} {}'.format(title, lastname)

# Apply the function to the list of people using map
result = list(map(split_title_and_name, people))
print(result)


TypeError: 'list' object is not callable

In [2]:
# 19. Show the use of lambda functions

dx = lambda x: x * 2

print(dx(10))

# 20.Show the use of lambda functions

dx = lambda x, y: (x + y)*2

print(dx(5, 10))

# 21. What will be the output of the following

my_list = [1, 5, 4, 6, 8, 11, 3, 12]

new_list1 = list(map(lambda x: x * 2 , my_list))

new_list2 = map(lambda x: x * 2 , my_list)

print(new_list1)
print(list(new_list2))


20
30
[2, 10, 8, 12, 16, 22, 6, 24]
[2, 10, 8, 12, 16, 22, 6, 24]


In [3]:
# 22. Iterate from 0 to 19 and return the even numbers

my_list = []
for number in range(1, 19):
    if number % 2 == 0:
        my_list.append(number)
my_list

#Now the same thing but with list comprehension
my_list = [number for number in range(1, 19) if number % 2 == 0]
my_list

# 23. Write the output of the following function.

def times_tables():
    lst = []
    for i in range(10):
        for j in range (10):
            lst.append(i*j)
    return lst

times_tables() == [j*i for i in range(10) for j in range(10)]

print(times_tables())
print([j*i for i in range(10) for j in range(10)])


[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]
[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 0, 2, 4, 6, 8, 10, 12, 14, 16, 18, 0, 3, 6, 9, 12, 15, 18, 21, 24, 27, 0, 4, 8, 12, 16, 20, 24, 28, 32, 36, 0, 5, 10, 15, 20, 25, 30, 35, 40, 45, 0, 6, 12, 18, 24, 30, 36, 42, 48, 54, 0, 7, 14, 21, 28, 35, 42, 49, 56, 63, 0, 8, 16, 24, 32, 40, 48, 56, 64, 72, 0, 9, 18, 27, 36, 45, 54, 63, 72, 81]


In [10]:
#24. Numerical Python (NumPy): Write the output of the following

import numpy as np
mylist = [1, 2, 3]
x = np.array(mylist)
#(a) what will be the value of x
print(x)

#Pass in a list of lists to create a multidimensional array.
m = np.array([[7, 8, 9], 
              [10, 11, 12]])
print(m)
#(c) Find the shape of the array m
print(m.shape)


[1 2 3]
[[ 7  8  9]
 [10 11 12]]
(2, 3)


In [13]:
#consider the following code
n = np.arange(0, 30, 2) 

# (a) write the value of n 
n
# (b) Reshape an array n to be 3x5 
reshaped=n.reshape(3,5)
reshaped

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28]])

In [15]:
#linspace returns evenly spaced numbers over a specified interval.
lspace = np.linspace(0, 10, 9) 
# (a) what will be the output of above code 
lspace

array([ 0.  ,  1.25,  2.5 ,  3.75,  5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [17]:
lspace.resize(3, 3)
# (a) what will be the output of above code
lspace

array([[ 0.  ,  1.25,  2.5 ],
       [ 3.75,  5.  ,  6.25],
       [ 7.5 ,  8.75, 10.  ]])

In [23]:
#ones returns a new array of given shape and type, filled with ones.
np.ones((5, 4))
#zeros returns a new array of given shape and type, filled with zeros.
np.zeros((2, 3))
#eye returns a 2-D array with ones on the diagonal and zeros elsewhere.
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [24]:
# matrix creation by array input
num = np.matrix([[11, 121, 130], 
                 [613 ,34, 13], 
                 [514, 50, 16]])

print("Main Diagnol elements : \n", np.diag(num))
print("\nDiagnol elements above main diagnol : \n", np.diag(num, 1) )
print("\nDiagnol elements below main diagnol : \n", np.diag(num, -1))

Main Diagnol elements : 
 [11 34 16]

Diagnol elements above main diagnol : 
 [121  13]

Diagnol elements below main diagnol : 
 [613  50]


In [27]:
# 25. Write the difference between the following two lines

#np.array([1, 2, 3] * 3)
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [34]:
# 26. Write the output of the following


p = np.ones([3, 3], int)


#np.vstack([p, 2*p])

np.vstack([p, 2*p, 3*p])

np.hstack([p, 2*p])

np.hstack([p, 2*p, 3*p])

array([[1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3],
       [1, 1, 1, 2, 2, 2, 3, 3, 3]])

In [37]:
# 27. Observe the output of the following 

x=np.array([1, 2, 3])
y=np.array([4, 5, 6])

print(x + y) 
print(x - y) 

print(x * y) 
print(x / y) 
print(x**2) 

x.dot(y) 

z = np.array([y, y**2])

z.T

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]


array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [ ]:







# 28. Write the output of the following

# 	a = np.array([-4, -2, 1, 3, 5])
# 	a.sum()

# 	a.max()

# 	a.min()

# 	a.mean()

# 	a.std()  

# 	a.argmax()

# 	a.argmin()



In [41]:
#29. Consider the following
s = np.arange(100)

#what will be the output of the following:
s = np.arange(6)**2

s[0], s[4], s[-1]

s[1:5]

array([ 1,  4,  9, 16])

In [42]:


#30. Consider the following
s = np.arange(13)**2

#what will be the output of the following:
s[0], s[4], s[-1]
s[1:5]
s[-4:]

s[-5::-2]
s[-5:-2]

array([ 64,  81, 100])

In [43]:
#31. Let's look at a multidimensional array.
r = np.arange(100)
r.resize((10, 10))

#what will be the output of 
r

r[2, 2]

r[3, 3:6]

r[:2, :-1]
r[-1, ::2]

r[r > 30]

r[r > 30] = 30
r



array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30],
       [30, 30, 30, 30, 30, 30, 30, 30, 30, 30]])

In [44]:
#32. Examine the output of the following code part

#r2 is a slice of r
r2 = r[:3,:3]
r2
#Set this slice's values to zero ([:] selects the entire array)
r2[:] = 0
r2

#r has also been changed!
r

#To avoid this, use r.copy to create a copy that will not affect the original array
r_copy = r.copy()
r_copy

#Now when r_copy is modified, r will not be changed.
r_copy[:] = 10
print(r_copy, '\n')
print(r)

[[10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]
 [10 10 10 10 10 10 10 10 10 10]] 

[[ 0  0  0  3  4  5  6  7  8  9]
 [ 0  0  0 13 14 15 16 17 18 19]
 [ 0  0  0 23 24 25 26 27 28 29]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]
 [30 30 30 30 30 30 30 30 30 30]]


In [1]:
# 32. Examine the output of the following code part

#r2 is a slice of r
r2 = r[:3,:3]
r2
#Set this slice's values to zero ([:] selects the entire array)
r2[:] = 0
r2

#r has also been changed!
r

#To avoid this, use r.copy to create a copy that will not affect the original array
r_copy = r.copy()
r_copy

#Now when r_copy is modified, r will not be changed.
r_copy[:] = 10
print(r_copy, '\n')
print(r)

#33. Iterating Over Arrays
#Let's create a new 4 by 3 array of random numbers 0-9.
test = np.random.randint(0, 10, (4,3))
test

#Iterate by row:
for row in test:
    print(row)

#Iterate by index:
for i in range(len(test)):
    print(test[i])

#Iterate by row and index:
for i, row in enumerate(test):
    print('row', i, 'is', row)

#Use zip to iterate over multiple iterables.
test2 = test**2
test2

for i, j in zip(test, test2):
    print(i,'+',j,'=',i+j)


NameError: name 'r' is not defined