In [ ]:
#for connect the colab to our drive
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).


In [ ]:
### read and display the dataset
import pandas as pd
data=pd.read_csv ("/content/drive/MyDrive/Colab Notebooks/FML/Data.csv")
dataset=data
dataset

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [ ]:
#split [Create matrix of all independent variables]
x=dataset.iloc[:,:-1].values
x

#np.shape(x)
#type(x)


array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#Spliting the dependent variables
y=dataset.iloc[:,3].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

In [ ]:
#Taking care of missing data
from sklearn.impute import SimpleImputer
import numpy as np
imputer= SimpleImputer(missing_values=np.nan,strategy='mean')
imputer=imputer.fit(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [ ]:
#encoding categorical data
#encoding independent variables
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labrlencoder_x=LabelEncoder()
x[:,0]=labrlencoder_x.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [ ]:
#encoding for the independent variable
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import  OneHotEncoder
ct= ColumnTransformer([("Country",OneHotEncoder(),[0])],remainder="passthrough")

x=ct.fit_transform(x)
x=x.astype(int)
x


array([[    1,     0,     0,    44, 72000],
       [    0,     0,     1,    27, 48000],
       [    0,     1,     0,    30, 54000],
       [    0,     0,     1,    38, 61000],
       [    0,     1,     0,    40, 63777],
       [    1,     0,     0,    35, 58000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     1,     0,    50, 83000],
       [    1,     0,     0,    37, 67000]])

In [ ]:
#encoding depending variables
labelencoder_y=LabelEncoder()
y=labelencoder_y.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [ ]:
#split data into training set and test set

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(x,y,test_size=0.2, random_state=0)
#random state=0 implies


In [ ]:
X_test.astype(int)
X_test

array([[    0,     1,     0,    30, 54000],
       [    0,     1,     0,    50, 83000]])

In [ ]:
X_train.astype(int)

array([[    0,     1,     0,    40, 63777],
       [    1,     0,     0,    37, 67000],
       [    0,     0,     1,    27, 48000],
       [    0,     0,     1,    38, 52000],
       [    1,     0,     0,    48, 79000],
       [    0,     0,     1,    38, 61000],
       [    1,     0,     0,    44, 72000],
       [    1,     0,     0,    35, 58000]])

In [ ]:
#Featuring Scaling
#sc_x = (X[1]-mean)/ standard deviation
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
X_train = sc_X.fit_transform(X_train)
X_test = sc_X.transform(X_test)


In [ ]:
X_train

(array([[-1.        ,  2.64575131, -0.77459667,  0.27978024,  0.12374357],
        [ 1.        , -0.37796447, -0.77459667, -0.23673712,  0.4617671 ],
        [-1.        , -0.37796447,  1.29099445, -1.95846165, -1.53092514],
        [-1.        , -0.37796447,  1.29099445, -0.06456467, -1.11141099],
        [ 1.        , -0.37796447, -0.77459667,  1.65715986,  1.72030956],
        [-1.        , -0.37796447,  1.29099445, -0.06456467, -0.16750414],
        [ 1.        , -0.37796447, -0.77459667,  0.96847005,  0.98615979],
        [ 1.        , -0.37796447, -0.77459667, -0.58108203, -0.48213975]]),)

In [ ]:
X_test

array([[-1.        ,  2.64575131, -0.77459667, -1.44194429, -0.90165391],
       [-1.        ,  2.64575131, -0.77459667,  2.00150476,  2.13982372]])